# Generated by Django 4.2.8 on 2023-12-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_openalexconcept_rename_element_element_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openalexconcept',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
