# Generated by Django 4.2.8 on 2023-12-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_openalexconcept_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='openalexconcept',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
