# Generated by Django 4.2.8 on 2023-12-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_openalexconcept_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='doi',
            field=models.CharField(max_length=100),
        ),
    ]
